project_id = "unpnuonbndubcuzxfnmg"

[functions.mapbox-geocoding]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.generate-enhanced-pdf]
verify_jwt = true

[functions.run-scheduled-reports]
verify_jwt = false

[functions.generate-customer-email]
verify_jwt = false