
project_id = "unpnuonbndubcuzxfnmg"

[functions.fleet-docs]
verify_jwt = false

[functions.customer-docs]
verify_jwt = false

[functions.taxjar-rate]
verify_jwt = false

[functions.notify-incident]
verify_jwt = false

