project_id = "unpnuonbndubcuzxfnmg"

[functions.fleet-docs]
verify_jwt = false

[functions.customer-docs]
verify_jwt = false

[functions.taxjar-rate]
verify_jwt = false

[functions.notify-incident]
verify_jwt = false

[functions.get-current-weather]
verify_jwt = false

[functions.search-gas-stations]
verify_jwt = false

[functions.search-gas-stations-google]
verify_jwt = false

[functions.check-document-expirations]
verify_jwt = false

[functions.suggest-document-category]
verify_jwt = false

[functions.send-fuel-notifications]
verify_jwt = false

