project_id = "kbqxyotasszslacozcey"

[functions.org-invite]
verify_jwt = false

[functions.profile_sync]
verify_jwt = false

[functions.get_role]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.trigger-job-assignment]
verify_jwt = false

[functions.trigger-invoice-reminder]
verify_jwt = false

[functions.trigger-maintenance-alert]
verify_jwt = false

[functions.trigger-low-stock-alert]
verify_jwt = false
